find_package(nlohmann_json QUIET)
if(NOT nlohmann_json_FOUND)
    cmake_policy(PUSH)
    # Avoid warning related to FetchContent and DOWNLOAD_EXTRACT_TIMESTAMP
    if(POLICY CMP0135)
        cmake_policy(SET CMP0135 NEW)
    endif()
    if(NOT COMMAND FetchContent_Declare)
        include(FetchContent)
    endif()
    FetchContent_Declare(json GIT_REPOSITORY https://github.com/nlohmann/json)
    FetchContent_MakeAvailable(json)
    cmake_policy(POP)
endif()
target_link_libraries(${PROJECT_NAME} INTERFACE nlohmann_json::nlohmann_json)
